<?php
/**
 * QualificationDocumentsApiCreation
 * PHP version 5
 *
 * @category Class
 * @package  TM\Saphety\Clientv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TM\Saphety\Clientv2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use TM\Saphety\Clientv2\ApiException;
use TM\Saphety\Clientv2\Configuration;
use TM\Saphety\Clientv2\HeaderSelector;
use TM\Saphety\Clientv2\ObjectSerializer;

/**
 * QualificationDocumentsApiCreation Class Doc Comment
 *
 * @category Class
 * @package  TM\Saphety\Clientv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QualificationDocumentsApiCreation
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation submitCreditNoteAsync
     *
     * Submit a credit note for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\CreditNoteInputDto $credit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \TM\Saphety\Clientv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto
     */
    public function submitCreditNoteAsync($virtual_operator, $credit_note = null, $in_transport_document_id = null)
    {
        list($response) = $this->submitCreditNoteAsyncWithHttpInfo($virtual_operator, $credit_note, $in_transport_document_id);
        return $response;
    }

    /**
     * Operation submitCreditNoteAsyncWithHttpInfo
     *
     * Submit a credit note for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\CreditNoteInputDto $credit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \TM\Saphety\Clientv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function submitCreditNoteAsyncWithHttpInfo($virtual_operator, $credit_note = null, $in_transport_document_id = null)
    {
        $returnType = '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto';
        $request = $this->submitCreditNoteAsyncRequest($virtual_operator, $credit_note, $in_transport_document_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation submitCreditNoteAsyncAsync
     *
     * Submit a credit note for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\CreditNoteInputDto $credit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitCreditNoteAsyncAsync($virtual_operator, $credit_note = null, $in_transport_document_id = null)
    {
        return $this->submitCreditNoteAsyncAsyncWithHttpInfo($virtual_operator, $credit_note, $in_transport_document_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation submitCreditNoteAsyncAsyncWithHttpInfo
     *
     * Submit a credit note for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\CreditNoteInputDto $credit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitCreditNoteAsyncAsyncWithHttpInfo($virtual_operator, $credit_note = null, $in_transport_document_id = null)
    {
        $returnType = '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto';
        $request = $this->submitCreditNoteAsyncRequest($virtual_operator, $credit_note, $in_transport_document_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'submitCreditNoteAsync'
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\CreditNoteInputDto $credit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function submitCreditNoteAsyncRequest($virtual_operator, $credit_note = null, $in_transport_document_id = null)
    {
        // verify the required parameter 'virtual_operator' is set
        if ($virtual_operator === null || (is_array($virtual_operator) && count($virtual_operator) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $virtual_operator when calling submitCreditNoteAsync'
            );
        }
        if (strlen($virtual_operator) > 60) {
            throw new \InvalidArgumentException('invalid length for "$virtual_operator" when calling QualificationDocumentsApiCreation.submitCreditNoteAsync, must be smaller than or equal to 60.');
        }


        $resourcePath = '/v2/{virtualOperator}/qualificationoutbounddocuments/creditNoteAsync';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($in_transport_document_id !== null) {
            $queryParams['inTransportDocumentId'] = ObjectSerializer::toQueryValue($in_transport_document_id);
        }

        // path params
        if ($virtual_operator !== null) {
            $resourcePath = str_replace(
                '{' . 'virtualOperator' . '}',
                ObjectSerializer::toPathValue($virtual_operator),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($credit_note)) {
            $_tempBody = $credit_note;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation submitDebitNoteAsync
     *
     * Submit a debit note for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\DebitNoteInputDto $debit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \TM\Saphety\Clientv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto
     */
    public function submitDebitNoteAsync($virtual_operator, $debit_note = null, $in_transport_document_id = null)
    {
        list($response) = $this->submitDebitNoteAsyncWithHttpInfo($virtual_operator, $debit_note, $in_transport_document_id);
        return $response;
    }

    /**
     * Operation submitDebitNoteAsyncWithHttpInfo
     *
     * Submit a debit note for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\DebitNoteInputDto $debit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \TM\Saphety\Clientv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function submitDebitNoteAsyncWithHttpInfo($virtual_operator, $debit_note = null, $in_transport_document_id = null)
    {
        $returnType = '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto';
        $request = $this->submitDebitNoteAsyncRequest($virtual_operator, $debit_note, $in_transport_document_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation submitDebitNoteAsyncAsync
     *
     * Submit a debit note for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\DebitNoteInputDto $debit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitDebitNoteAsyncAsync($virtual_operator, $debit_note = null, $in_transport_document_id = null)
    {
        return $this->submitDebitNoteAsyncAsyncWithHttpInfo($virtual_operator, $debit_note, $in_transport_document_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation submitDebitNoteAsyncAsyncWithHttpInfo
     *
     * Submit a debit note for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\DebitNoteInputDto $debit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitDebitNoteAsyncAsyncWithHttpInfo($virtual_operator, $debit_note = null, $in_transport_document_id = null)
    {
        $returnType = '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto';
        $request = $this->submitDebitNoteAsyncRequest($virtual_operator, $debit_note, $in_transport_document_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'submitDebitNoteAsync'
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\DebitNoteInputDto $debit_note  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function submitDebitNoteAsyncRequest($virtual_operator, $debit_note = null, $in_transport_document_id = null)
    {
        // verify the required parameter 'virtual_operator' is set
        if ($virtual_operator === null || (is_array($virtual_operator) && count($virtual_operator) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $virtual_operator when calling submitDebitNoteAsync'
            );
        }
        if (strlen($virtual_operator) > 60) {
            throw new \InvalidArgumentException('invalid length for "$virtual_operator" when calling QualificationDocumentsApiCreation.submitDebitNoteAsync, must be smaller than or equal to 60.');
        }


        $resourcePath = '/v2/{virtualOperator}/qualificationoutbounddocuments/debitNoteAsync';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($in_transport_document_id !== null) {
            $queryParams['inTransportDocumentId'] = ObjectSerializer::toQueryValue($in_transport_document_id);
        }

        // path params
        if ($virtual_operator !== null) {
            $resourcePath = str_replace(
                '{' . 'virtualOperator' . '}',
                ObjectSerializer::toPathValue($virtual_operator),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($debit_note)) {
            $_tempBody = $debit_note;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation submitSalesInvoiceAsync
     *
     * Submit an invoice for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\SalesInvoiceInputDto $sales_invoice  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \TM\Saphety\Clientv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto
     */
    public function submitSalesInvoiceAsync($virtual_operator, $sales_invoice = null, $in_transport_document_id = null)
    {
        list($response) = $this->submitSalesInvoiceAsyncWithHttpInfo($virtual_operator, $sales_invoice, $in_transport_document_id);
        return $response;
    }

    /**
     * Operation submitSalesInvoiceAsyncWithHttpInfo
     *
     * Submit an invoice for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\SalesInvoiceInputDto $sales_invoice  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \TM\Saphety\Clientv2\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function submitSalesInvoiceAsyncWithHttpInfo($virtual_operator, $sales_invoice = null, $in_transport_document_id = null)
    {
        $returnType = '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto';
        $request = $this->submitSalesInvoiceAsyncRequest($virtual_operator, $sales_invoice, $in_transport_document_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation submitSalesInvoiceAsyncAsync
     *
     * Submit an invoice for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\SalesInvoiceInputDto $sales_invoice  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitSalesInvoiceAsyncAsync($virtual_operator, $sales_invoice = null, $in_transport_document_id = null)
    {
        return $this->submitSalesInvoiceAsyncAsyncWithHttpInfo($virtual_operator, $sales_invoice, $in_transport_document_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation submitSalesInvoiceAsyncAsyncWithHttpInfo
     *
     * Submit an invoice for qualification
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\SalesInvoiceInputDto $sales_invoice  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function submitSalesInvoiceAsyncAsyncWithHttpInfo($virtual_operator, $sales_invoice = null, $in_transport_document_id = null)
    {
        $returnType = '\TM\Saphety\Clientv2\Model\ResultMessageQualificationDocumentResultDto';
        $request = $this->submitSalesInvoiceAsyncRequest($virtual_operator, $sales_invoice, $in_transport_document_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'submitSalesInvoiceAsync'
     *
     * @param  string $virtual_operator MaxLength: 60 (required)
     * @param  \TM\Saphety\Clientv2\Model\SalesInvoiceInputDto $sales_invoice  (optional)
     * @param  string $in_transport_document_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function submitSalesInvoiceAsyncRequest($virtual_operator, $sales_invoice = null, $in_transport_document_id = null)
    {
        // verify the required parameter 'virtual_operator' is set
        if ($virtual_operator === null || (is_array($virtual_operator) && count($virtual_operator) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $virtual_operator when calling submitSalesInvoiceAsync'
            );
        }
        if (strlen($virtual_operator) > 60) {
            throw new \InvalidArgumentException('invalid length for "$virtual_operator" when calling QualificationDocumentsApiCreation.submitSalesInvoiceAsync, must be smaller than or equal to 60.');
        }


        $resourcePath = '/v2/{virtualOperator}/qualificationoutbounddocuments/salesInvoiceAsync';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($in_transport_document_id !== null) {
            $queryParams['inTransportDocumentId'] = ObjectSerializer::toQueryValue($in_transport_document_id);
        }

        // path params
        if ($virtual_operator !== null) {
            $resourcePath = str_replace(
                '{' . 'virtualOperator' . '}',
                ObjectSerializer::toPathValue($virtual_operator),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($sales_invoice)) {
            $_tempBody = $sales_invoice;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
