<?php
/**
 * CudeInputDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocumentsQuery
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CudeInputDto Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CudeInputDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CudeInputDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'issue_date' => 'string',
        'customer_document_number' => 'string',
        'issuer_nit_number' => 'string',
        'document_number' => 'string',
        'total_iva' => 'string',
        'total_inc' => 'string',
        'total_ica' => 'string',
        'total_gross_amount' => 'string',
        'total_payable_amount' => 'string',
        'supplier_time_zone_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'issue_date' => null,
        'customer_document_number' => null,
        'issuer_nit_number' => null,
        'document_number' => null,
        'total_iva' => null,
        'total_inc' => null,
        'total_ica' => null,
        'total_gross_amount' => null,
        'total_payable_amount' => null,
        'supplier_time_zone_code' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'issue_date' => 'IssueDate',
        'customer_document_number' => 'CustomerDocumentNumber',
        'issuer_nit_number' => 'IssuerNitNumber',
        'document_number' => 'DocumentNumber',
        'total_iva' => 'TotalIva',
        'total_inc' => 'TotalInc',
        'total_ica' => 'TotalIca',
        'total_gross_amount' => 'TotalGrossAmount',
        'total_payable_amount' => 'TotalPayableAmount',
        'supplier_time_zone_code' => 'SupplierTimeZoneCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'issue_date' => 'setIssueDate',
        'customer_document_number' => 'setCustomerDocumentNumber',
        'issuer_nit_number' => 'setIssuerNitNumber',
        'document_number' => 'setDocumentNumber',
        'total_iva' => 'setTotalIva',
        'total_inc' => 'setTotalInc',
        'total_ica' => 'setTotalIca',
        'total_gross_amount' => 'setTotalGrossAmount',
        'total_payable_amount' => 'setTotalPayableAmount',
        'supplier_time_zone_code' => 'setSupplierTimeZoneCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'issue_date' => 'getIssueDate',
        'customer_document_number' => 'getCustomerDocumentNumber',
        'issuer_nit_number' => 'getIssuerNitNumber',
        'document_number' => 'getDocumentNumber',
        'total_iva' => 'getTotalIva',
        'total_inc' => 'getTotalInc',
        'total_ica' => 'getTotalIca',
        'total_gross_amount' => 'getTotalGrossAmount',
        'total_payable_amount' => 'getTotalPayableAmount',
        'supplier_time_zone_code' => 'getSupplierTimeZoneCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['issue_date'] = isset($data['issue_date']) ? $data['issue_date'] : null;
        $this->container['customer_document_number'] = isset($data['customer_document_number']) ? $data['customer_document_number'] : null;
        $this->container['issuer_nit_number'] = isset($data['issuer_nit_number']) ? $data['issuer_nit_number'] : null;
        $this->container['document_number'] = isset($data['document_number']) ? $data['document_number'] : null;
        $this->container['total_iva'] = isset($data['total_iva']) ? $data['total_iva'] : null;
        $this->container['total_inc'] = isset($data['total_inc']) ? $data['total_inc'] : null;
        $this->container['total_ica'] = isset($data['total_ica']) ? $data['total_ica'] : null;
        $this->container['total_gross_amount'] = isset($data['total_gross_amount']) ? $data['total_gross_amount'] : null;
        $this->container['total_payable_amount'] = isset($data['total_payable_amount']) ? $data['total_payable_amount'] : null;
        $this->container['supplier_time_zone_code'] = isset($data['supplier_time_zone_code']) ? $data['supplier_time_zone_code'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['issue_date'] === null) {
            $invalidProperties[] = "'issue_date' can't be null";
        }
        if ($this->container['customer_document_number'] === null) {
            $invalidProperties[] = "'customer_document_number' can't be null";
        }
        if ($this->container['issuer_nit_number'] === null) {
            $invalidProperties[] = "'issuer_nit_number' can't be null";
        }
        if ($this->container['document_number'] === null) {
            $invalidProperties[] = "'document_number' can't be null";
        }
        if ($this->container['total_iva'] === null) {
            $invalidProperties[] = "'total_iva' can't be null";
        }
        if ($this->container['total_inc'] === null) {
            $invalidProperties[] = "'total_inc' can't be null";
        }
        if ($this->container['total_ica'] === null) {
            $invalidProperties[] = "'total_ica' can't be null";
        }
        if ($this->container['total_gross_amount'] === null) {
            $invalidProperties[] = "'total_gross_amount' can't be null";
        }
        if ($this->container['total_payable_amount'] === null) {
            $invalidProperties[] = "'total_payable_amount' can't be null";
        }
        if ($this->container['supplier_time_zone_code'] === null) {
            $invalidProperties[] = "'supplier_time_zone_code' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets issue_date
     *
     * @return string
     */
    public function getIssueDate()
    {
        return $this->container['issue_date'];
    }

    /**
     * Sets issue_date
     *
     * @param string $issue_date issue_date
     *
     * @return $this
     */
    public function setIssueDate($issue_date)
    {
        $this->container['issue_date'] = $issue_date;

        return $this;
    }

    /**
     * Gets customer_document_number
     *
     * @return string
     */
    public function getCustomerDocumentNumber()
    {
        return $this->container['customer_document_number'];
    }

    /**
     * Sets customer_document_number
     *
     * @param string $customer_document_number customer_document_number
     *
     * @return $this
     */
    public function setCustomerDocumentNumber($customer_document_number)
    {
        $this->container['customer_document_number'] = $customer_document_number;

        return $this;
    }

    /**
     * Gets issuer_nit_number
     *
     * @return string
     */
    public function getIssuerNitNumber()
    {
        return $this->container['issuer_nit_number'];
    }

    /**
     * Sets issuer_nit_number
     *
     * @param string $issuer_nit_number issuer_nit_number
     *
     * @return $this
     */
    public function setIssuerNitNumber($issuer_nit_number)
    {
        $this->container['issuer_nit_number'] = $issuer_nit_number;

        return $this;
    }

    /**
     * Gets document_number
     *
     * @return string
     */
    public function getDocumentNumber()
    {
        return $this->container['document_number'];
    }

    /**
     * Sets document_number
     *
     * @param string $document_number document_number
     *
     * @return $this
     */
    public function setDocumentNumber($document_number)
    {
        $this->container['document_number'] = $document_number;

        return $this;
    }

    /**
     * Gets total_iva
     *
     * @return string
     */
    public function getTotalIva()
    {
        return $this->container['total_iva'];
    }

    /**
     * Sets total_iva
     *
     * @param string $total_iva total_iva
     *
     * @return $this
     */
    public function setTotalIva($total_iva)
    {
        $this->container['total_iva'] = $total_iva;

        return $this;
    }

    /**
     * Gets total_inc
     *
     * @return string
     */
    public function getTotalInc()
    {
        return $this->container['total_inc'];
    }

    /**
     * Sets total_inc
     *
     * @param string $total_inc total_inc
     *
     * @return $this
     */
    public function setTotalInc($total_inc)
    {
        $this->container['total_inc'] = $total_inc;

        return $this;
    }

    /**
     * Gets total_ica
     *
     * @return string
     */
    public function getTotalIca()
    {
        return $this->container['total_ica'];
    }

    /**
     * Sets total_ica
     *
     * @param string $total_ica total_ica
     *
     * @return $this
     */
    public function setTotalIca($total_ica)
    {
        $this->container['total_ica'] = $total_ica;

        return $this;
    }

    /**
     * Gets total_gross_amount
     *
     * @return string
     */
    public function getTotalGrossAmount()
    {
        return $this->container['total_gross_amount'];
    }

    /**
     * Sets total_gross_amount
     *
     * @param string $total_gross_amount total_gross_amount
     *
     * @return $this
     */
    public function setTotalGrossAmount($total_gross_amount)
    {
        $this->container['total_gross_amount'] = $total_gross_amount;

        return $this;
    }

    /**
     * Gets total_payable_amount
     *
     * @return string
     */
    public function getTotalPayableAmount()
    {
        return $this->container['total_payable_amount'];
    }

    /**
     * Sets total_payable_amount
     *
     * @param string $total_payable_amount total_payable_amount
     *
     * @return $this
     */
    public function setTotalPayableAmount($total_payable_amount)
    {
        $this->container['total_payable_amount'] = $total_payable_amount;

        return $this;
    }

    /**
     * Gets supplier_time_zone_code
     *
     * @return string
     */
    public function getSupplierTimeZoneCode()
    {
        return $this->container['supplier_time_zone_code'];
    }

    /**
     * Sets supplier_time_zone_code
     *
     * @param string $supplier_time_zone_code supplier_time_zone_code
     *
     * @return $this
     */
    public function setSupplierTimeZoneCode($supplier_time_zone_code)
    {
        $this->container['supplier_time_zone_code'] = $supplier_time_zone_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


