<?php
/**
 * LineInputDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  TM\Saphety\Clientv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace TM\Saphety\Clientv2\Model;

use \ArrayAccess;
use \TM\Saphety\Clientv2\ObjectSerializer;

/**
 * LineInputDto Class Doc Comment
 *
 * @category Class
 * @package  TM\Saphety\Clientv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LineInputDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'LineInputDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'number' => 'string',
        'accounting_cost_code' => 'string',
        'quantity' => 'string',
        'quantity_unit_of_measure' => 'string',
        'tax_sub_totals' => '\TM\Saphety\Clientv2\Model\TaxSubTotalInputDto[]',
        'tax_totals' => '\TM\Saphety\Clientv2\Model\TaxTotalInputDto[]',
        'exclude_vat' => 'string',
        'withholding_tax_sub_totals' => '\TM\Saphety\Clientv2\Model\WithholdingTaxSubTotalInputDto[]',
        'withholding_tax_totals' => '\TM\Saphety\Clientv2\Model\WithholdingTaxTotalInputDto[]',
        'unit_price' => 'string',
        'gross_amount' => 'string',
        'net_amount' => 'string',
        'allowance_charges' => '\TM\Saphety\Clientv2\Model\AllowanceChargeInputDto[]',
        'document_references' => '\TM\Saphety\Clientv2\Model\DocumentReferenceInputDto[]',
        'document_line_references' => '\TM\Saphety\Clientv2\Model\DocumentLineReferenceInputDto[]',
        'item' => '\TM\Saphety\Clientv2\Model\ItemInputDto',
        'note' => 'string',
        'delivery' => '\TM\Saphety\Clientv2\Model\DeliveryInputDto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'number' => null,
        'accounting_cost_code' => null,
        'quantity' => null,
        'quantity_unit_of_measure' => null,
        'tax_sub_totals' => null,
        'tax_totals' => null,
        'exclude_vat' => null,
        'withholding_tax_sub_totals' => null,
        'withholding_tax_totals' => null,
        'unit_price' => null,
        'gross_amount' => null,
        'net_amount' => null,
        'allowance_charges' => null,
        'document_references' => null,
        'document_line_references' => null,
        'item' => null,
        'note' => null,
        'delivery' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'number' => 'Number',
        'accounting_cost_code' => 'AccountingCostCode',
        'quantity' => 'Quantity',
        'quantity_unit_of_measure' => 'QuantityUnitOfMeasure',
        'tax_sub_totals' => 'TaxSubTotals',
        'tax_totals' => 'TaxTotals',
        'exclude_vat' => 'ExcludeVat',
        'withholding_tax_sub_totals' => 'WithholdingTaxSubTotals',
        'withholding_tax_totals' => 'WithholdingTaxTotals',
        'unit_price' => 'UnitPrice',
        'gross_amount' => 'GrossAmount',
        'net_amount' => 'NetAmount',
        'allowance_charges' => 'AllowanceCharges',
        'document_references' => 'DocumentReferences',
        'document_line_references' => 'DocumentLineReferences',
        'item' => 'Item',
        'note' => 'Note',
        'delivery' => 'Delivery'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'number' => 'setNumber',
        'accounting_cost_code' => 'setAccountingCostCode',
        'quantity' => 'setQuantity',
        'quantity_unit_of_measure' => 'setQuantityUnitOfMeasure',
        'tax_sub_totals' => 'setTaxSubTotals',
        'tax_totals' => 'setTaxTotals',
        'exclude_vat' => 'setExcludeVat',
        'withholding_tax_sub_totals' => 'setWithholdingTaxSubTotals',
        'withholding_tax_totals' => 'setWithholdingTaxTotals',
        'unit_price' => 'setUnitPrice',
        'gross_amount' => 'setGrossAmount',
        'net_amount' => 'setNetAmount',
        'allowance_charges' => 'setAllowanceCharges',
        'document_references' => 'setDocumentReferences',
        'document_line_references' => 'setDocumentLineReferences',
        'item' => 'setItem',
        'note' => 'setNote',
        'delivery' => 'setDelivery'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'number' => 'getNumber',
        'accounting_cost_code' => 'getAccountingCostCode',
        'quantity' => 'getQuantity',
        'quantity_unit_of_measure' => 'getQuantityUnitOfMeasure',
        'tax_sub_totals' => 'getTaxSubTotals',
        'tax_totals' => 'getTaxTotals',
        'exclude_vat' => 'getExcludeVat',
        'withholding_tax_sub_totals' => 'getWithholdingTaxSubTotals',
        'withholding_tax_totals' => 'getWithholdingTaxTotals',
        'unit_price' => 'getUnitPrice',
        'gross_amount' => 'getGrossAmount',
        'net_amount' => 'getNetAmount',
        'allowance_charges' => 'getAllowanceCharges',
        'document_references' => 'getDocumentReferences',
        'document_line_references' => 'getDocumentLineReferences',
        'item' => 'getItem',
        'note' => 'getNote',
        'delivery' => 'getDelivery'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['accounting_cost_code'] = isset($data['accounting_cost_code']) ? $data['accounting_cost_code'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['quantity_unit_of_measure'] = isset($data['quantity_unit_of_measure']) ? $data['quantity_unit_of_measure'] : null;
        $this->container['tax_sub_totals'] = isset($data['tax_sub_totals']) ? $data['tax_sub_totals'] : null;
        $this->container['tax_totals'] = isset($data['tax_totals']) ? $data['tax_totals'] : null;
        $this->container['exclude_vat'] = isset($data['exclude_vat']) ? $data['exclude_vat'] : null;
        $this->container['withholding_tax_sub_totals'] = isset($data['withholding_tax_sub_totals']) ? $data['withholding_tax_sub_totals'] : null;
        $this->container['withholding_tax_totals'] = isset($data['withholding_tax_totals']) ? $data['withholding_tax_totals'] : null;
        $this->container['unit_price'] = isset($data['unit_price']) ? $data['unit_price'] : null;
        $this->container['gross_amount'] = isset($data['gross_amount']) ? $data['gross_amount'] : null;
        $this->container['net_amount'] = isset($data['net_amount']) ? $data['net_amount'] : null;
        $this->container['allowance_charges'] = isset($data['allowance_charges']) ? $data['allowance_charges'] : null;
        $this->container['document_references'] = isset($data['document_references']) ? $data['document_references'] : null;
        $this->container['document_line_references'] = isset($data['document_line_references']) ? $data['document_line_references'] : null;
        $this->container['item'] = isset($data['item']) ? $data['item'] : null;
        $this->container['note'] = isset($data['note']) ? $data['note'] : null;
        $this->container['delivery'] = isset($data['delivery']) ? $data['delivery'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['number'] === null) {
            $invalidProperties[] = "'number' can't be null";
        }
        if (!is_null($this->container['accounting_cost_code']) && (mb_strlen($this->container['accounting_cost_code']) > 20)) {
            $invalidProperties[] = "invalid value for 'accounting_cost_code', the character length must be smaller than or equal to 20.";
        }

        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ($this->container['quantity_unit_of_measure'] === null) {
            $invalidProperties[] = "'quantity_unit_of_measure' can't be null";
        }
        if ($this->container['unit_price'] === null) {
            $invalidProperties[] = "'unit_price' can't be null";
        }
        if ($this->container['gross_amount'] === null) {
            $invalidProperties[] = "'gross_amount' can't be null";
        }
        if ($this->container['net_amount'] === null) {
            $invalidProperties[] = "'net_amount' can't be null";
        }
        if ($this->container['item'] === null) {
            $invalidProperties[] = "'item' can't be null";
        }
        if (!is_null($this->container['note']) && (mb_strlen($this->container['note']) > 500)) {
            $invalidProperties[] = "invalid value for 'note', the character length must be smaller than or equal to 500.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string $number number
     *
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets accounting_cost_code
     *
     * @return string
     */
    public function getAccountingCostCode()
    {
        return $this->container['accounting_cost_code'];
    }

    /**
     * Sets accounting_cost_code
     *
     * @param string $accounting_cost_code MaxLength: 20
     *
     * @return $this
     */
    public function setAccountingCostCode($accounting_cost_code)
    {
        if (!is_null($accounting_cost_code) && (mb_strlen($accounting_cost_code) > 20)) {
            throw new \InvalidArgumentException('invalid length for $accounting_cost_code when calling LineInputDto., must be smaller than or equal to 20.');
        }

        $this->container['accounting_cost_code'] = $accounting_cost_code;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return string
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param string $quantity quantity
     *
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets quantity_unit_of_measure
     *
     * @return string
     */
    public function getQuantityUnitOfMeasure()
    {
        return $this->container['quantity_unit_of_measure'];
    }

    /**
     * Sets quantity_unit_of_measure
     *
     * @param string $quantity_unit_of_measure quantity_unit_of_measure
     *
     * @return $this
     */
    public function setQuantityUnitOfMeasure($quantity_unit_of_measure)
    {
        $this->container['quantity_unit_of_measure'] = $quantity_unit_of_measure;

        return $this;
    }

    /**
     * Gets tax_sub_totals
     *
     * @return \TM\Saphety\Clientv2\Model\TaxSubTotalInputDto[]
     */
    public function getTaxSubTotals()
    {
        return $this->container['tax_sub_totals'];
    }

    /**
     * Sets tax_sub_totals
     *
     * @param \TM\Saphety\Clientv2\Model\TaxSubTotalInputDto[] $tax_sub_totals tax_sub_totals
     *
     * @return $this
     */
    public function setTaxSubTotals($tax_sub_totals)
    {
        $this->container['tax_sub_totals'] = $tax_sub_totals;

        return $this;
    }

    /**
     * Gets tax_totals
     *
     * @return \TM\Saphety\Clientv2\Model\TaxTotalInputDto[]
     */
    public function getTaxTotals()
    {
        return $this->container['tax_totals'];
    }

    /**
     * Sets tax_totals
     *
     * @param \TM\Saphety\Clientv2\Model\TaxTotalInputDto[] $tax_totals tax_totals
     *
     * @return $this
     */
    public function setTaxTotals($tax_totals)
    {
        $this->container['tax_totals'] = $tax_totals;

        return $this;
    }

    /**
     * Gets exclude_vat
     *
     * @return string
     */
    public function getExcludeVat()
    {
        return $this->container['exclude_vat'];
    }

    /**
     * Sets exclude_vat
     *
     * @param string $exclude_vat exclude_vat
     *
     * @return $this
     */
    public function setExcludeVat($exclude_vat)
    {
        $this->container['exclude_vat'] = $exclude_vat;

        return $this;
    }

    /**
     * Gets withholding_tax_sub_totals
     *
     * @return \TM\Saphety\Clientv2\Model\WithholdingTaxSubTotalInputDto[]
     */
    public function getWithholdingTaxSubTotals()
    {
        return $this->container['withholding_tax_sub_totals'];
    }

    /**
     * Sets withholding_tax_sub_totals
     *
     * @param \TM\Saphety\Clientv2\Model\WithholdingTaxSubTotalInputDto[] $withholding_tax_sub_totals withholding_tax_sub_totals
     *
     * @return $this
     */
    public function setWithholdingTaxSubTotals($withholding_tax_sub_totals)
    {
        $this->container['withholding_tax_sub_totals'] = $withholding_tax_sub_totals;

        return $this;
    }

    /**
     * Gets withholding_tax_totals
     *
     * @return \TM\Saphety\Clientv2\Model\WithholdingTaxTotalInputDto[]
     */
    public function getWithholdingTaxTotals()
    {
        return $this->container['withholding_tax_totals'];
    }

    /**
     * Sets withholding_tax_totals
     *
     * @param \TM\Saphety\Clientv2\Model\WithholdingTaxTotalInputDto[] $withholding_tax_totals withholding_tax_totals
     *
     * @return $this
     */
    public function setWithholdingTaxTotals($withholding_tax_totals)
    {
        $this->container['withholding_tax_totals'] = $withholding_tax_totals;

        return $this;
    }

    /**
     * Gets unit_price
     *
     * @return string
     */
    public function getUnitPrice()
    {
        return $this->container['unit_price'];
    }

    /**
     * Sets unit_price
     *
     * @param string $unit_price unit_price
     *
     * @return $this
     */
    public function setUnitPrice($unit_price)
    {
        $this->container['unit_price'] = $unit_price;

        return $this;
    }

    /**
     * Gets gross_amount
     *
     * @return string
     */
    public function getGrossAmount()
    {
        return $this->container['gross_amount'];
    }

    /**
     * Sets gross_amount
     *
     * @param string $gross_amount gross_amount
     *
     * @return $this
     */
    public function setGrossAmount($gross_amount)
    {
        $this->container['gross_amount'] = $gross_amount;

        return $this;
    }

    /**
     * Gets net_amount
     *
     * @return string
     */
    public function getNetAmount()
    {
        return $this->container['net_amount'];
    }

    /**
     * Sets net_amount
     *
     * @param string $net_amount net_amount
     *
     * @return $this
     */
    public function setNetAmount($net_amount)
    {
        $this->container['net_amount'] = $net_amount;

        return $this;
    }

    /**
     * Gets allowance_charges
     *
     * @return \TM\Saphety\Clientv2\Model\AllowanceChargeInputDto[]
     */
    public function getAllowanceCharges()
    {
        return $this->container['allowance_charges'];
    }

    /**
     * Sets allowance_charges
     *
     * @param \TM\Saphety\Clientv2\Model\AllowanceChargeInputDto[] $allowance_charges allowance_charges
     *
     * @return $this
     */
    public function setAllowanceCharges($allowance_charges)
    {
        $this->container['allowance_charges'] = $allowance_charges;

        return $this;
    }

    /**
     * Gets document_references
     *
     * @return \TM\Saphety\Clientv2\Model\DocumentReferenceInputDto[]
     */
    public function getDocumentReferences()
    {
        return $this->container['document_references'];
    }

    /**
     * Sets document_references
     *
     * @param \TM\Saphety\Clientv2\Model\DocumentReferenceInputDto[] $document_references document_references
     *
     * @return $this
     */
    public function setDocumentReferences($document_references)
    {
        $this->container['document_references'] = $document_references;

        return $this;
    }

    /**
     * Gets document_line_references
     *
     * @return \TM\Saphety\Clientv2\Model\DocumentLineReferenceInputDto[]
     */
    public function getDocumentLineReferences()
    {
        return $this->container['document_line_references'];
    }

    /**
     * Sets document_line_references
     *
     * @param \TM\Saphety\Clientv2\Model\DocumentLineReferenceInputDto[] $document_line_references document_line_references
     *
     * @return $this
     */
    public function setDocumentLineReferences($document_line_references)
    {
        $this->container['document_line_references'] = $document_line_references;

        return $this;
    }

    /**
     * Gets item
     *
     * @return \TM\Saphety\Clientv2\Model\ItemInputDto
     */
    public function getItem()
    {
        return $this->container['item'];
    }

    /**
     * Sets item
     *
     * @param \TM\Saphety\Clientv2\Model\ItemInputDto $item item
     *
     * @return $this
     */
    public function setItem($item)
    {
        $this->container['item'] = $item;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string $note MaxLength: 500
     *
     * @return $this
     */
    public function setNote($note)
    {
        if (!is_null($note) && (mb_strlen($note) > 500)) {
            throw new \InvalidArgumentException('invalid length for $note when calling LineInputDto., must be smaller than or equal to 500.');
        }

        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets delivery
     *
     * @return \TM\Saphety\Clientv2\Model\DeliveryInputDto
     */
    public function getDelivery()
    {
        return $this->container['delivery'];
    }

    /**
     * Sets delivery
     *
     * @param \TM\Saphety\Clientv2\Model\DeliveryInputDto $delivery delivery
     *
     * @return $this
     */
    public function setDelivery($delivery)
    {
        $this->container['delivery'] = $delivery;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


