<?php
/**
 * CustomerPartyInputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomerPartyInputDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerPartyInputDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerPartyInputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomerPartyInputDto"
     */
    public function testCustomerPartyInputDto()
    {
    }

    /**
     * Test attribute "tele_fax"
     */
    public function testPropertyTeleFax()
    {
    }

    /**
     * Test attribute "document_contacts"
     */
    public function testPropertyDocumentContacts()
    {
    }

    /**
     * Test attribute "gln"
     */
    public function testPropertyGln()
    {
    }

    /**
     * Test attribute "legal_type"
     */
    public function testPropertyLegalType()
    {
    }

    /**
     * Test attribute "identification"
     */
    public function testPropertyIdentification()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "website_url"
     */
    public function testPropertyWebsiteUrl()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "tax_scheme"
     */
    public function testPropertyTaxScheme()
    {
    }

    /**
     * Test attribute "person"
     */
    public function testPropertyPerson()
    {
    }

    /**
     * Test attribute "industry"
     */
    public function testPropertyIndustry()
    {
    }

    /**
     * Test attribute "responsability_types"
     */
    public function testPropertyResponsabilityTypes()
    {
    }
}
