<?php
/**
 * DocumentSearchCriteriaInputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocumentsQuery
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DocumentSearchCriteriaInputDtoTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentSearchCriteriaInputDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentSearchCriteriaInputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentSearchCriteriaInputDto"
     */
    public function testDocumentSearchCriteriaInputDto()
    {
    }

    /**
     * Test attribute "document_number"
     */
    public function testPropertyDocumentNumber()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "company_ids"
     */
    public function testPropertyCompanyIds()
    {
    }

    /**
     * Test attribute "virtual_operator_ids"
     */
    public function testPropertyVirtualOperatorIds()
    {
    }

    /**
     * Test attribute "suppliers"
     */
    public function testPropertySuppliers()
    {
    }

    /**
     * Test attribute "customers"
     */
    public function testPropertyCustomers()
    {
    }

    /**
     * Test attribute "document_types"
     */
    public function testPropertyDocumentTypes()
    {
    }

    /**
     * Test attribute "document_sub_types"
     */
    public function testPropertyDocumentSubTypes()
    {
    }

    /**
     * Test attribute "document_status"
     */
    public function testPropertyDocumentStatus()
    {
    }

    /**
     * Test attribute "communication_status"
     */
    public function testPropertyCommunicationStatus()
    {
    }

    /**
     * Test attribute "main_email_notification_status"
     */
    public function testPropertyMainEmailNotificationStatus()
    {
    }

    /**
     * Test attribute "creation_date_start"
     */
    public function testPropertyCreationDateStart()
    {
    }

    /**
     * Test attribute "creation_date_end"
     */
    public function testPropertyCreationDateEnd()
    {
    }

    /**
     * Test attribute "document_date_start"
     */
    public function testPropertyDocumentDateStart()
    {
    }

    /**
     * Test attribute "document_date_end"
     */
    public function testPropertyDocumentDateEnd()
    {
    }

    /**
     * Test attribute "offset"
     */
    public function testPropertyOffset()
    {
    }

    /**
     * Test attribute "number_of_records"
     */
    public function testPropertyNumberOfRecords()
    {
    }

    /**
     * Test attribute "sort_field"
     */
    public function testPropertySortField()
    {
    }
}
