<?php
/**
 * DocumentSearchServiceOutputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocumentsQuery
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DocumentSearchServiceOutputDtoTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentSearchServiceOutputDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentSearchServiceOutputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentSearchServiceOutputDto"
     */
    public function testDocumentSearchServiceOutputDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "document_sub_type"
     */
    public function testPropertyDocumentSubType()
    {
    }

    /**
     * Test attribute "document_number"
     */
    public function testPropertyDocumentNumber()
    {
    }

    /**
     * Test attribute "origin_id"
     */
    public function testPropertyOriginId()
    {
    }

    /**
     * Test attribute "origin_name"
     */
    public function testPropertyOriginName()
    {
    }

    /**
     * Test attribute "origin_code"
     */
    public function testPropertyOriginCode()
    {
    }

    /**
     * Test attribute "destination_id"
     */
    public function testPropertyDestinationId()
    {
    }

    /**
     * Test attribute "destination_name"
     */
    public function testPropertyDestinationName()
    {
    }

    /**
     * Test attribute "destination_code"
     */
    public function testPropertyDestinationCode()
    {
    }

    /**
     * Test attribute "document_date"
     */
    public function testPropertyDocumentDate()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "document_status"
     */
    public function testPropertyDocumentStatus()
    {
    }

    /**
     * Test attribute "document_status_date"
     */
    public function testPropertyDocumentStatusDate()
    {
    }

    /**
     * Test attribute "communication_status"
     */
    public function testPropertyCommunicationStatus()
    {
    }

    /**
     * Test attribute "communication_status_comments"
     */
    public function testPropertyCommunicationStatusComments()
    {
    }

    /**
     * Test attribute "main_email_notification"
     */
    public function testPropertyMainEmailNotification()
    {
    }

    /**
     * Test attribute "main_email_notification_status"
     */
    public function testPropertyMainEmailNotificationStatus()
    {
    }

    /**
     * Test attribute "main_email_notification_status_reason"
     */
    public function testPropertyMainEmailNotificationStatusReason()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "cufe"
     */
    public function testPropertyCufe()
    {
    }
}
