<?php
/**
 * LegalMonetaryTotalInputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LegalMonetaryTotalInputDtoTest Class Doc Comment
 *
 * @category    Class
 * @description LegalMonetaryTotalInputDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LegalMonetaryTotalInputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LegalMonetaryTotalInputDto"
     */
    public function testLegalMonetaryTotalInputDto()
    {
    }

    /**
     * Test attribute "gross_amount"
     */
    public function testPropertyGrossAmount()
    {
    }

    /**
     * Test attribute "total_billable_amount"
     */
    public function testPropertyTotalBillableAmount()
    {
    }

    /**
     * Test attribute "total_billable_rounding_amount"
     */
    public function testPropertyTotalBillableRoundingAmount()
    {
    }

    /**
     * Test attribute "payable_amount"
     */
    public function testPropertyPayableAmount()
    {
    }

    /**
     * Test attribute "taxable_amount"
     */
    public function testPropertyTaxableAmount()
    {
    }

    /**
     * Test attribute "allowances_total_amount"
     */
    public function testPropertyAllowancesTotalAmount()
    {
    }

    /**
     * Test attribute "charges_total_amount"
     */
    public function testPropertyChargesTotalAmount()
    {
    }

    /**
     * Test attribute "pre_paid_total_amount"
     */
    public function testPropertyPrePaidTotalAmount()
    {
    }
}
