<?php
/**
 * LineInputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LineInputDtoTest Class Doc Comment
 *
 * @category    Class
 * @description LineInputDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LineInputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LineInputDto"
     */
    public function testLineInputDto()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "accounting_cost_code"
     */
    public function testPropertyAccountingCostCode()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "quantity_unit_of_measure"
     */
    public function testPropertyQuantityUnitOfMeasure()
    {
    }

    /**
     * Test attribute "tax_sub_totals"
     */
    public function testPropertyTaxSubTotals()
    {
    }

    /**
     * Test attribute "tax_totals"
     */
    public function testPropertyTaxTotals()
    {
    }

    /**
     * Test attribute "exclude_vat"
     */
    public function testPropertyExcludeVat()
    {
    }

    /**
     * Test attribute "withholding_tax_sub_totals"
     */
    public function testPropertyWithholdingTaxSubTotals()
    {
    }

    /**
     * Test attribute "withholding_tax_totals"
     */
    public function testPropertyWithholdingTaxTotals()
    {
    }

    /**
     * Test attribute "unit_price"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "gross_amount"
     */
    public function testPropertyGrossAmount()
    {
    }

    /**
     * Test attribute "net_amount"
     */
    public function testPropertyNetAmount()
    {
    }

    /**
     * Test attribute "allowance_charges"
     */
    public function testPropertyAllowanceCharges()
    {
    }

    /**
     * Test attribute "document_references"
     */
    public function testPropertyDocumentReferences()
    {
    }

    /**
     * Test attribute "document_line_references"
     */
    public function testPropertyDocumentLineReferences()
    {
    }

    /**
     * Test attribute "item"
     */
    public function testPropertyItem()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {
    }
}
