<?php
/**
 * SalesInvoiceInputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SalesInvoiceInputDtoTest Class Doc Comment
 *
 * @category    Class
 * @description SalesInvoiceInputDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesInvoiceInputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SalesInvoiceInputDto"
     */
    public function testSalesInvoiceInputDto()
    {
    }

    /**
     * Test attribute "billing_period"
     */
    public function testPropertyBillingPeriod()
    {
    }

    /**
     * Test attribute "delivery_terms"
     */
    public function testPropertyDeliveryTerms()
    {
    }

    /**
     * Test attribute "withholding_tax_sub_totals"
     */
    public function testPropertyWithholdingTaxSubTotals()
    {
    }

    /**
     * Test attribute "withholding_tax_totals"
     */
    public function testPropertyWithholdingTaxTotals()
    {
    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "serie_prefix"
     */
    public function testPropertySeriePrefix()
    {
    }

    /**
     * Test attribute "serie_number"
     */
    public function testPropertySerieNumber()
    {
    }

    /**
     * Test attribute "issuer_party"
     */
    public function testPropertyIssuerParty()
    {
    }

    /**
     * Test attribute "customer_party"
     */
    public function testPropertyCustomerParty()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }

    /**
     * Test attribute "tax_sub_totals"
     */
    public function testPropertyTaxSubTotals()
    {
    }

    /**
     * Test attribute "tax_totals"
     */
    public function testPropertyTaxTotals()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "issue_date"
     */
    public function testPropertyIssueDate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "external_reference"
     */
    public function testPropertyExternalReference()
    {
    }

    /**
     * Test attribute "correlation_document_id"
     */
    public function testPropertyCorrelationDocumentId()
    {
    }

    /**
     * Test attribute "serie_external_key"
     */
    public function testPropertySerieExternalKey()
    {
    }

    /**
     * Test attribute "additional_notification_emails"
     */
    public function testPropertyAdditionalNotificationEmails()
    {
    }

    /**
     * Test attribute "document_references"
     */
    public function testPropertyDocumentReferences()
    {
    }

    /**
     * Test attribute "graphical_representation_custom_fields"
     */
    public function testPropertyGraphicalRepresentationCustomFields()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "pdf_data"
     */
    public function testPropertyPdfData()
    {
    }

    /**
     * Test attribute "prepaid_payments"
     */
    public function testPropertyPrepaidPayments()
    {
    }

    /**
     * Test attribute "payment_exchange_rate"
     */
    public function testPropertyPaymentExchangeRate()
    {
    }

    /**
     * Test attribute "payment_means"
     */
    public function testPropertyPaymentMeans()
    {
    }

    /**
     * Test attribute "payment_terms"
     */
    public function testPropertyPaymentTerms()
    {
    }

    /**
     * Test attribute "allowance_charges"
     */
    public function testPropertyAllowanceCharges()
    {
    }

    /**
     * Test attribute "operation_type"
     */
    public function testPropertyOperationType()
    {
    }
}
