<?php
/**
 * TaxSubTotalInputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TaxSubTotalInputDtoTest Class Doc Comment
 *
 * @category    Class
 * @description TaxSubTotalInputDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaxSubTotalInputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TaxSubTotalInputDto"
     */
    public function testTaxSubTotalInputDto()
    {
    }

    /**
     * Test attribute "tax_category"
     */
    public function testPropertyTaxCategory()
    {
    }

    /**
     * Test attribute "tax_percentage"
     */
    public function testPropertyTaxPercentage()
    {
    }

    /**
     * Test attribute "taxable_amount"
     */
    public function testPropertyTaxableAmount()
    {
    }

    /**
     * Test attribute "tax_amount"
     */
    public function testPropertyTaxAmount()
    {
    }

    /**
     * Test attribute "per_unit_amount"
     */
    public function testPropertyPerUnitAmount()
    {
    }

    /**
     * Test attribute "base_unit_measure"
     */
    public function testPropertyBaseUnitMeasure()
    {
    }

    /**
     * Test attribute "base_unit_measure_unit_measure"
     */
    public function testPropertyBaseUnitMeasureUnitMeasure()
    {
    }
}
