<?php
/**
 * TestPdfTemplateInputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TestPdfTemplateInputDtoTest Class Doc Comment
 *
 * @category    Class
 * @description TestPdfTemplateInputDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TestPdfTemplateInputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TestPdfTemplateInputDto"
     */
    public function testTestPdfTemplateInputDto()
    {
    }

    /**
     * Test attribute "dto"
     */
    public function testPropertyDto()
    {
    }

    /**
     * Test attribute "ubl"
     */
    public function testPropertyUbl()
    {
    }

    /**
     * Test attribute "pdf_template"
     */
    public function testPropertyPdfTemplate()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "document_sub_type"
     */
    public function testPropertyDocumentSubType()
    {
    }

    /**
     * Test attribute "language_code"
     */
    public function testPropertyLanguageCode()
    {
    }
}
