<?php
/**
 * DocumentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OutboundDocuments
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCreditNote
     *
     * Creates a Credit Note.
     *
     */
    public function testCreateCreditNote()
    {
    }

    /**
     * Test case for createCreditNoteAsync
     *
     * Creates an Credit Note asynchronously.
     *
     */
    public function testCreateCreditNoteAsync()
    {
    }

    /**
     * Test case for createDebitNote
     *
     * Creates a Debit Note.
     *
     */
    public function testCreateDebitNote()
    {
    }

    /**
     * Test case for createDebitNoteAsync
     *
     * Creates an Debit Note asynchronously.
     *
     */
    public function testCreateDebitNoteAsync()
    {
    }

    /**
     * Test case for createSalesInvoice
     *
     * Creates an Invoice.
     *
     */
    public function testCreateSalesInvoice()
    {
    }

    /**
     * Test case for createSalesInvoiceAsync
     *
     * Creates an Invoice asynchronously.
     *
     */
    public function testCreateSalesInvoiceAsync()
    {
    }
}
